# run_parameters
run_p:
  pretrain_lr: &pretrain_lr 0.03
  ft_lr: &ft_lr 30.0
  pretrain_batch_size: 256
  ft_batch_size: 256
  val_batch_size: 256
  pretrain_epoch: &pretrain_epoch 200
  ft_epoch: &ft_epoch 100
  network: MoCo
  dataset: &dataset IN1000
  optimizer: &op SGD

#model
model:
  type: ResNet
  features_dim: 128
  maxpool: True
  depth: 50
moco:
  type: MoCo
  dim: 128
  K: 65536
  m: 0.999
  T: 0.07
  mlp: False

# run_device
run_d :
  num_workers: 12

# criterion, loss
loss:
  pretrain:
    type: CrossEntropyLoss
  ft:
    type: CrossEntropyLoss

# optimizer
op:
  pretrain:
    type: *op
    lr: *pretrain_lr
    momentum: 0.9
    weight_decay: 0.0001
  ft:
    type: *op
    lr: *ft_lr
    momentum: 0.9
    weight_decay: 0

# dataset
dataset:
  root: ../../../mnt/e/ILSVRC2012
  type: *dataset
  num_classes: 1000
  pretrain:
    type: IN1000_rcrop_stepcovering
    transform:
      type: IN1000_train_rcrop_singlestepdecovering
      cover_interval: 20
      division_num: 4
      step_decover: 12
      cover_num: 12
      mean: 0.485, 0.456, 0.406
      std: 0.229, 0.224, 0.225
  ft:
    transform:
      type: IN1000_linear
      mean: 0.485, 0.456, 0.406
      std: 0.229, 0.224, 0.225
  val:
    transform:
      type: IN1000_test
      mean: 0.485, 0.456, 0.406
      std: 0.229, 0.224, 0.225

# adjust lr
lr_cfg:
  pretrain :
    type: Cosine
    steps: *pretrain_epoch
    lr: *pretrain_lr
    decay_rate: 0
    re_lr: 20
    warmup_steps: 0
  ft :
    type: MultiStep
    steps: *ft_epoch
    lr: *ft_lr
    decay_rate: 0.1
    decay_steps:
      - 60
      - 80

port: 10001
save_interval:
  pretrain: 100
  ft: 50