# run_parameters
run_p:
  pretrain_lr: &pretrain_lr 0.5
  ft_lr: &ft_lr 10.0
  pretrain_batch_size: 512
  ft_batch_size: 512
  val_batch_size: 512
  pretrain_epoch: &pretrain_epoch 500
  ft_epoch: &ft_epoch 100
  network: MoCo #  For information display only
  dataset: &dataset CIFAR10 # dataset list CIFAR10, CIFAR100, Tiny200, IN1000
  optimizer: &op SGD

#model
model:
  type: ResNet
  features_dim: 128
  maxpool: False
  depth: 18
moco:
  type: MoCo
  dim: 128
  K: 65536
  m: 0.999
  T: 0.20
  mlp: True

run_d :
  num_workers: 4

# criterion, loss
loss:
  pretrain:
    type: CrossEntropyLoss
  ft:
    type: CrossEntropyLoss

# optimizer
op:
  pretrain:
    type: *op
    lr: *pretrain_lr
    momentum: 0.9
    weight_decay: 0.0001
  ft:
    type: *op
    lr: *ft_lr
    momentum: 0.9
    weight_decay: 0

# dataset
dataset:
  root: ./data
  type: *dataset
  num_classes: 10 #only used for linear classification
  pretrain:
#    different methods need different 'type'
#    default(rcrop and cutout) => CIFAR10_rcrop
#    lsc and lsc+cutout => CIFAR10_rcrop_stepcovering
#    c-crop => CIFAR10_ccrop
#    c-crop+lsc => CIFAR10_ccrop_stepcovering
    type: CIFAR10_rcrop
    train: True
#    different methods are applied in the transform configuration
#    rcrop
    transform:
      type: cifar_train_rcrop
      mean: 0.4914, 0.4822, 0.4465
      std: 0.2023, 0.1994, 0.2010
#    rcrop end

#    cutout
    transform:
      type: cifar_train_rcrop_singlercovering
      ratio: 0.3
      division_num: 3
      mean: 0.5071, 0.4867, 0.4408
      std: 0.2675, 0.2565, 0.2761
#    cutout end

#    LSC
    transform:
      type: cifar_train_rcrop_singlestepdecovering
      cover_interval: &ci 50
      division_num: 4
      step_decover: 12
      cover_num: 12
      mean: 0.5071, 0.4867, 0.4408
      std: 0.2675, 0.2565, 0.2761
#    LSC end

#    ccrop+LSC
  transform_rcrop:
    type: cifar_train_rcrop_singlestepdecovering
    cover_interval: 50
    division_num: 4
    step_decover: 12
    cover_num: 12
    mean: 0.5071, 0.4867, 0.4408
    std: 0.2675, 0.2565, 0.2761
  transform_ccrop:
    type: cifar_train_ccrop
    alpha: 0.1
    mean: 0.5071, 0.4867, 0.4408
    std: 0.2675, 0.2565, 0.2761
#    ccrop+LSC end

  ft:
    train: True
    transform:
      type: cifar_linear
      mean: 0.4914, 0.4822, 0.4465
      std: 0.2023, 0.1994, 0.2010
  val:
    train: False
    transform:
      type: cifar_test
      mean: 0.4914, 0.4822, 0.4465
      std: 0.2023, 0.1994, 0.2010

# adjust lr
lr_cfg:
  pretrain :
    type: Cosine
    steps: *pretrain_epoch
    lr: *pretrain_lr
    decay_rate: 0.07
    re_lr: *ci # only used fot LSC, default 0
    warmup_steps: 0
  ft :
    type: MultiStep
    steps: *ft_epoch
    lr: *ft_lr
    decay_rate: 0.1
    decay_steps:
      - 60
      - 80

port: 10001
save_interval:
#  int => save every 250 epoch
  pretrain: 250
#  list => save when epoch == number in list
  pretrain:
    - 50
    - 250
  ft: 50